version: '3'
services:
  br-news-bot-service:
    build:
      dockerfile: conf/Dockerfile
      context: ./
    command: python -m service
    volumes:
      - type: bind
        source: ./src/
        target: /app
    networks:
      - uf-network
    env_file:
      - conf/env/db.dev.env
      - conf/env/app.dev.env
      - conf/env/rabbitmq.dev.env
    ports:
      - 9050:9050
    depends_on:
      br-news-bot-db:
        condition: service_healthy
  
  br-news-bot-db:
    image: postgres:alpine
    env_file:
      - conf/env/db.dev.env
    ports:
      - 5434:5432
    networks:
      - uf-network
    volumes:
      - br-news-bot-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  br-news-bot-db-data:
    
networks:
  uf-network:
    driver: bridge
