version: '3'
services:
  br-news-bot-service:
    build:
      dockerfile: conf/Dockerfile
      context: ./
    command: python -m service
    volumes:
      - type: bind
        source: ./src/
        target: /app
    networks:
      - uf-network
    env_file:
      - conf/env/db.dev.env
      - conf/env/app.dev.env
      - conf/env/rabbitmq.dev.env
    ports:
      - 9050:9050
    depends_on:
      br-news-bot-db:
        condition: service_healthy
  
  br-news-bot-db:
    image: postgres:alpine
    env_file:
      - conf/env/db.dev.env
    ports:
      - 5432:5432
    networks:
      - uf-network
    volumes:
      - br-news-bot-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # <name>-rabbitmq:
  #   image: rabbitmq:3-management-alpine
  #   container_name: 'rabbitmq'
  #   ports:
  #       - 5672:5672
  #       - 15672:15672
  #   volumes:
  #       - <name>-rabbitmq/data/:/var/lib/rabbitmq/
  #       - <name>-rabbitmq/log/:/var/log/rabbitmq/
  #   networks:
  #       - uf-network

volumes:
  br-news-bot-db-data:
  # <name>-rabbitmq/data:
  # <name>-rabbitmq/log:
    
networks:
  uf-network:
    driver: bridge
